-- ==========================================================
-- SKRIP SETUP DATABASE SUPABASE (POSTGRESQL)
-- Sistem Monitoring & Prediksi Potensi Banjir (IoT & Fuzzy)
-- ==========================================================
-- Petunjuk:
-- 1. Buka dashboard Supabase (https://supabase.com).
-- 2. Pilih project Anda > Buka menu "SQL Editor" di bilah kiri.
-- 3. Tempel (paste) seluruh skrip di bawah ini, lalu klik "RUN".
-- ==========================================================

-- 1. Tabel Konfigurasi Sistem
CREATE TABLE IF NOT EXISTS tb_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_key VARCHAR(50) UNIQUE NOT NULL,
    config_value TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Data Default tb_config
INSERT INTO tb_config (config_key, config_value) VALUES
('refresh_interval', '5000'),
('alert_threshold_aman', '40'),
('alert_threshold_bahaya', '60')
ON CONFLICT (config_key) DO NOTHING;


-- 2. Tabel Utama: Data Sensor Curah Hujan
CREATE TABLE IF NOT EXISTS tb_sensor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    curah_hujan REAL NOT NULL,
    durasi_hujan INT NOT NULL,
    intensitas_hujan REAL NOT NULL,
    potensi_banjir REAL,
    status_banjir VARCHAR(20),
    kategori_hujan VARCHAR(20),
    kejadian_hari INT DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Buat index untuk kecepatan pencarian data terbaru berdasarkan waktu
CREATE INDEX IF NOT EXISTS idx_tb_sensor_created_at ON tb_sensor(created_at DESC);


-- 3. Tabel Log Inferensi Fuzzy
CREATE TABLE IF NOT EXISTS tb_fuzzy_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    curah_hujan REAL,
    durasi_hujan INT,
    intensitas_hujan REAL,
    derajat_rendah REAL,
    derajat_sedang REAL,
    derajat_tinggi REAL,
    durasi_singkat REAL,
    durasi_sedang REAL,
    durasi_lama REAL,
    intensitas_rendah REAL,
    intensitas_sedang REAL,
    intensitas_tinggi REAL,
    output_fuzzy REAL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);


-- 4. View Rekapitulasi Harian Kejadian Hujan
CREATE OR REPLACE VIEW v_rekap_harian AS
SELECT 
    (created_at AT TIME ZONE 'Asia/Jakarta')::DATE AS tanggal,
    COUNT(*) AS jumlah_data,
    ROUND(SUM(curah_hujan)::NUMERIC, 1) AS total_curah,
    ROUND(AVG(curah_hujan)::NUMERIC, 1) AS rata_curah,
    MAX(potensi_banjir) AS skor_tertinggi,
    MIN(potensi_banjir) AS skor_terendah,
    ROUND(AVG(potensi_banjir)::NUMERIC, 1) AS skor_rata_rata,
    CASE 
        WHEN MAX(CASE WHEN status_banjir ILIKE '%BAHAYA%' THEN 3 WHEN status_banjir ILIKE '%WASPADA%' THEN 2 WHEN status_banjir ILIKE '%AMAN%' THEN 1 ELSE 0 END) = 3 THEN '🔴 BAHAYA'
        WHEN MAX(CASE WHEN status_banjir ILIKE '%BAHAYA%' THEN 3 WHEN status_banjir ILIKE '%WASPADA%' THEN 2 WHEN status_banjir ILIKE '%AMAN%' THEN 1 ELSE 0 END) = 2 THEN '🟡 WASPADA'
        ELSE '🟢 AMAN'
    END AS status_tertinggi
FROM tb_sensor
WHERE curah_hujan > 0
GROUP BY (created_at AT TIME ZONE 'Asia/Jakarta')::DATE
ORDER BY tanggal DESC;


-- 5. Hak Akses Tabel (Nonaktifkan Row Level Security agar API backend bebas membaca & menulis data)
ALTER TABLE tb_sensor DISABLE ROW LEVEL SECURITY;
ALTER TABLE tb_config DISABLE ROW LEVEL SECURITY;
ALTER TABLE tb_fuzzy_log DISABLE ROW LEVEL SECURITY;

-- Selesai! Tabel siap digunakan oleh backend Node.js dan Vercel.
